
name:  Security A
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with JIRA
        uses: github/codescanning-jira-integration@master
        with:
          jira_url: 'https://moiryan.atlassian.net'
          jira_user: 'hammymoh'
          jira_token: '${{ secrets.JiraApiToken }}'
          jira_project: 'SECMAN'
          sync_direction: 'gh2jira'


